---
- name: 
  hosts: all
  become: yes
  tasks: 
  - name: Update repositories
    apt:
      update_cache: yes

  - name: Install python full package
    apt:
      name: python3.9-full
      state: present

  - name: Install sound dependencies 
    apt:
      name: pulseaudio
      state: present

  - name: Ensure X11 is not using localhost
    lineinfile:
      create: yes
      line: X11UseLocalhost no
      owner: root
      state: present
      path: /etc/ssh/sshd_config.d/X11.conf

  - name: Restart sshd
    service:
      name: sshd
      state: restarted

