---
- name: 
  hosts: all
  become: yes
  tasks: 
  - name: Update repositories
    yum:
      update_cache: yes

  - name: Ensure X11 is not using localhost
    lineinfile:
      create: yes
      line: X11UseLocalhost no
      owner: root
      state: present
      path: /etc/ssh/sshd_config.d/X11.conf

  - name: Restart sshd
    service:
      name: sshd
      state: restarted

