---
- name: 
  hosts: all
  become: yes
  tasks: 
  - name: Update repositories
    apt:
      update_cache: yes
  - name: Install python full package
    apt:
      name: python3.9-full
      state: present
